// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module gray_kernel_write_stage (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        out_r_dout,
        out_r_num_data_valid,
        out_r_fifo_cap,
        out_r_empty_n,
        out_r_read,
        stream_out_dout,
        stream_out_num_data_valid,
        stream_out_fifo_cap,
        stream_out_empty_n,
        stream_out_read,
        num_pixels_dout,
        num_pixels_num_data_valid,
        num_pixels_fifo_cap,
        num_pixels_empty_n,
        num_pixels_read
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [7:0] m_axi_gmem_WDATA;
output  [0:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [7:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [10:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [63:0] out_r_dout;
input  [2:0] out_r_num_data_valid;
input  [2:0] out_r_fifo_cap;
input   out_r_empty_n;
output   out_r_read;
input  [7:0] stream_out_dout;
input  [8:0] stream_out_num_data_valid;
input  [8:0] stream_out_fifo_cap;
input   stream_out_empty_n;
output   stream_out_read;
input  [31:0] num_pixels_dout;
input  [2:0] num_pixels_num_data_valid;
input  [2:0] num_pixels_fifo_cap;
input   num_pixels_empty_n;
output   num_pixels_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem_AWVALID;
reg[63:0] m_axi_gmem_AWADDR;
reg[0:0] m_axi_gmem_AWID;
reg[31:0] m_axi_gmem_AWLEN;
reg[2:0] m_axi_gmem_AWSIZE;
reg[1:0] m_axi_gmem_AWBURST;
reg[1:0] m_axi_gmem_AWLOCK;
reg[3:0] m_axi_gmem_AWCACHE;
reg[2:0] m_axi_gmem_AWPROT;
reg[3:0] m_axi_gmem_AWQOS;
reg[3:0] m_axi_gmem_AWREGION;
reg[0:0] m_axi_gmem_AWUSER;
reg m_axi_gmem_WVALID;
reg m_axi_gmem_BREADY;
reg stream_out_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state2;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state9;
reg    out_r_blk_n;
reg    num_pixels_blk_n;
reg   [31:0] num_pixels_1_reg_107;
reg    ap_block_state1;
reg   [63:0] out_1_reg_112;
wire   [30:0] empty_fu_89_p3;
reg   [30:0] empty_reg_118;
wire    grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start;
wire    grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_done;
wire    grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_idle;
wire    grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_ready;
wire    grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_stream_out_read;
wire    grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWVALID;
wire   [63:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWADDR;
wire   [0:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWID;
wire   [31:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWLEN;
wire   [2:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWSIZE;
wire   [1:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWBURST;
wire   [1:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWLOCK;
wire   [3:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWCACHE;
wire   [2:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWPROT;
wire   [3:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWQOS;
wire   [3:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWREGION;
wire   [0:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWUSER;
wire    grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WVALID;
wire   [7:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WDATA;
wire   [0:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WSTRB;
wire    grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WLAST;
wire   [0:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WID;
wire   [0:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WUSER;
wire    grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARVALID;
wire   [63:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARADDR;
wire   [0:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARID;
wire   [31:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARLEN;
wire   [2:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARSIZE;
wire   [1:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARBURST;
wire   [1:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARLOCK;
wire   [3:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARCACHE;
wire   [2:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARPROT;
wire   [3:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARQOS;
wire   [3:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARREGION;
wire   [0:0] grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARUSER;
wire    grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_RREADY;
wire    grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_BREADY;
reg    grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire   [63:0] zext_ln38_fu_103_p1;
reg    num_pixels_read_local;
reg    out_r_read_local;
wire   [0:0] icmp_ln38_fu_79_p2;
wire   [30:0] trunc_ln38_fu_85_p1;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start_reg = 1'b0;
end

gray_kernel_write_stage_Pipeline_VITIS_LOOP_38_1 grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start),
    .ap_done(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_done),
    .ap_idle(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_idle),
    .ap_ready(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_ready),
    .stream_out_dout(stream_out_dout),
    .stream_out_num_data_valid(9'd0),
    .stream_out_fifo_cap(9'd0),
    .stream_out_empty_n(stream_out_empty_n),
    .stream_out_read(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_stream_out_read),
    .m_axi_gmem_AWVALID(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(m_axi_gmem_AWREADY),
    .m_axi_gmem_AWADDR(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(m_axi_gmem_WREADY),
    .m_axi_gmem_WDATA(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(1'b0),
    .m_axi_gmem_ARADDR(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(1'b0),
    .m_axi_gmem_RREADY(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(8'd0),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(11'd0),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(m_axi_gmem_BVALID),
    .m_axi_gmem_BREADY(grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(m_axi_gmem_BRESP),
    .m_axi_gmem_BID(m_axi_gmem_BID),
    .m_axi_gmem_BUSER(m_axi_gmem_BUSER),
    .num_pixels_1(num_pixels_1_reg_107),
    .out_1(out_1_reg_112)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((m_axi_gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start_reg <= 1'b1;
        end else if ((grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_ready == 1'b1)) begin
            grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        empty_reg_118 <= empty_fu_89_p3;
        num_pixels_1_reg_107 <= num_pixels_dout;
        out_1_reg_112 <= out_r_dout;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_gmem_AWREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem_BVALID == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((m_axi_gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_AWADDR = out_1_reg_112;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_AWADDR = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWADDR;
    end else begin
        m_axi_gmem_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_AWBURST = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWBURST;
    end else begin
        m_axi_gmem_AWBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_AWCACHE = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWCACHE;
    end else begin
        m_axi_gmem_AWCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_AWID = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWID;
    end else begin
        m_axi_gmem_AWID = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_AWLEN = zext_ln38_fu_103_p1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_AWLEN = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWLEN;
    end else begin
        m_axi_gmem_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_AWLOCK = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWLOCK;
    end else begin
        m_axi_gmem_AWLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_AWPROT = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWPROT;
    end else begin
        m_axi_gmem_AWPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_AWQOS = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWQOS;
    end else begin
        m_axi_gmem_AWQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_AWREGION = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWREGION;
    end else begin
        m_axi_gmem_AWREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_AWSIZE = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWSIZE;
    end else begin
        m_axi_gmem_AWSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_AWUSER = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWUSER;
    end else begin
        m_axi_gmem_AWUSER = 1'd0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_AWVALID = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_AWVALID;
    end else begin
        m_axi_gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        m_axi_gmem_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_BREADY = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_BREADY;
    end else begin
        m_axi_gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        m_axi_gmem_WVALID = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WVALID;
    end else begin
        m_axi_gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_pixels_blk_n = num_pixels_empty_n;
    end else begin
        num_pixels_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        num_pixels_read_local = 1'b1;
    end else begin
        num_pixels_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        out_r_blk_n = out_r_empty_n;
    end else begin
        out_r_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        out_r_read_local = 1'b1;
    end else begin
        out_r_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        stream_out_read = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_stream_out_read;
    end else begin
        stream_out_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((m_axi_gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((m_axi_gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((out_r_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0) | (num_pixels_empty_n == 1'b0));
end

assign empty_fu_89_p3 = ((icmp_ln38_fu_79_p2[0:0] == 1'b1) ? trunc_ln38_fu_85_p1 : 31'd0);

assign grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_ap_start_reg;

assign icmp_ln38_fu_79_p2 = (($signed(num_pixels_dout) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign m_axi_gmem_ARADDR = 64'd0;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd0;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_ARVALID = 1'b0;

assign m_axi_gmem_RREADY = 1'b0;

assign m_axi_gmem_WDATA = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WDATA;

assign m_axi_gmem_WID = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WID;

assign m_axi_gmem_WLAST = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WLAST;

assign m_axi_gmem_WSTRB = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WSTRB;

assign m_axi_gmem_WUSER = grp_write_stage_Pipeline_VITIS_LOOP_38_1_fu_69_m_axi_gmem_WUSER;

assign num_pixels_read = num_pixels_read_local;

assign out_r_read = out_r_read_local;

assign trunc_ln38_fu_85_p1 = num_pixels_dout[30:0];

assign zext_ln38_fu_103_p1 = empty_reg_118;

endmodule //gray_kernel_write_stage
