-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gray_kernel is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_CACHE_VALUE : INTEGER := 3 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_BUSER_WIDTH-1 downto 0) );
end;


architecture behav of gray_kernel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "gray_kernel_gray_kernel,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.920000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=5,HLS_SYN_DSP=0,HLS_SYN_FF=2088,HLS_SYN_LUT=2797,HLS_VERSION=2024_1}";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal in_r : STD_LOGIC_VECTOR (63 downto 0);
    signal out_r : STD_LOGIC_VECTOR (63 downto 0);
    signal num_pixels : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal gmem_AWREADY : STD_LOGIC;
    signal gmem_WREADY : STD_LOGIC;
    signal gmem_ARREADY : STD_LOGIC;
    signal gmem_RVALID : STD_LOGIC;
    signal gmem_RDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal gmem_RLAST : STD_LOGIC;
    signal gmem_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_RFIFONUM : STD_LOGIC_VECTOR (10 downto 0);
    signal gmem_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem_BVALID : STD_LOGIC;
    signal gmem_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal entry_proc_U0_ap_start : STD_LOGIC;
    signal entry_proc_U0_ap_done : STD_LOGIC;
    signal entry_proc_U0_ap_continue : STD_LOGIC;
    signal entry_proc_U0_ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_ready : STD_LOGIC;
    signal entry_proc_U0_start_out : STD_LOGIC;
    signal entry_proc_U0_start_write : STD_LOGIC;
    signal entry_proc_U0_out_r_c_din : STD_LOGIC_VECTOR (63 downto 0);
    signal entry_proc_U0_out_r_c_write : STD_LOGIC;
    signal read_stage_U0_ap_start : STD_LOGIC;
    signal read_stage_U0_ap_done : STD_LOGIC;
    signal read_stage_U0_ap_continue : STD_LOGIC;
    signal read_stage_U0_ap_idle : STD_LOGIC;
    signal read_stage_U0_ap_ready : STD_LOGIC;
    signal read_stage_U0_start_out : STD_LOGIC;
    signal read_stage_U0_start_write : STD_LOGIC;
    signal read_stage_U0_m_axi_gmem_AWVALID : STD_LOGIC;
    signal read_stage_U0_m_axi_gmem_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal read_stage_U0_m_axi_gmem_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_stage_U0_m_axi_gmem_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal read_stage_U0_m_axi_gmem_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal read_stage_U0_m_axi_gmem_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal read_stage_U0_m_axi_gmem_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal read_stage_U0_m_axi_gmem_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal read_stage_U0_m_axi_gmem_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal read_stage_U0_m_axi_gmem_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal read_stage_U0_m_axi_gmem_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal read_stage_U0_m_axi_gmem_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_stage_U0_m_axi_gmem_WVALID : STD_LOGIC;
    signal read_stage_U0_m_axi_gmem_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal read_stage_U0_m_axi_gmem_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal read_stage_U0_m_axi_gmem_WLAST : STD_LOGIC;
    signal read_stage_U0_m_axi_gmem_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_stage_U0_m_axi_gmem_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_stage_U0_m_axi_gmem_ARVALID : STD_LOGIC;
    signal read_stage_U0_m_axi_gmem_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal read_stage_U0_m_axi_gmem_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal read_stage_U0_m_axi_gmem_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal read_stage_U0_m_axi_gmem_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal read_stage_U0_m_axi_gmem_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal read_stage_U0_m_axi_gmem_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal read_stage_U0_m_axi_gmem_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal read_stage_U0_m_axi_gmem_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal read_stage_U0_m_axi_gmem_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal read_stage_U0_m_axi_gmem_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal read_stage_U0_m_axi_gmem_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal read_stage_U0_m_axi_gmem_RREADY : STD_LOGIC;
    signal read_stage_U0_m_axi_gmem_BREADY : STD_LOGIC;
    signal read_stage_U0_stream_in_din : STD_LOGIC_VECTOR (23 downto 0);
    signal read_stage_U0_stream_in_write : STD_LOGIC;
    signal read_stage_U0_num_pixels_c1_din : STD_LOGIC_VECTOR (31 downto 0);
    signal read_stage_U0_num_pixels_c1_write : STD_LOGIC;
    signal proc_stage_U0_ap_start : STD_LOGIC;
    signal proc_stage_U0_ap_done : STD_LOGIC;
    signal proc_stage_U0_ap_continue : STD_LOGIC;
    signal proc_stage_U0_ap_idle : STD_LOGIC;
    signal proc_stage_U0_ap_ready : STD_LOGIC;
    signal proc_stage_U0_stream_in_read : STD_LOGIC;
    signal proc_stage_U0_stream_out_din : STD_LOGIC_VECTOR (7 downto 0);
    signal proc_stage_U0_stream_out_write : STD_LOGIC;
    signal proc_stage_U0_num_pixels_read : STD_LOGIC;
    signal proc_stage_U0_num_pixels_c_din : STD_LOGIC_VECTOR (31 downto 0);
    signal proc_stage_U0_num_pixels_c_write : STD_LOGIC;
    signal write_stage_U0_ap_start : STD_LOGIC;
    signal write_stage_U0_ap_done : STD_LOGIC;
    signal write_stage_U0_ap_continue : STD_LOGIC;
    signal write_stage_U0_ap_idle : STD_LOGIC;
    signal write_stage_U0_ap_ready : STD_LOGIC;
    signal write_stage_U0_m_axi_gmem_AWVALID : STD_LOGIC;
    signal write_stage_U0_m_axi_gmem_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal write_stage_U0_m_axi_gmem_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal write_stage_U0_m_axi_gmem_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal write_stage_U0_m_axi_gmem_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal write_stage_U0_m_axi_gmem_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal write_stage_U0_m_axi_gmem_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal write_stage_U0_m_axi_gmem_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal write_stage_U0_m_axi_gmem_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal write_stage_U0_m_axi_gmem_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal write_stage_U0_m_axi_gmem_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal write_stage_U0_m_axi_gmem_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal write_stage_U0_m_axi_gmem_WVALID : STD_LOGIC;
    signal write_stage_U0_m_axi_gmem_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal write_stage_U0_m_axi_gmem_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal write_stage_U0_m_axi_gmem_WLAST : STD_LOGIC;
    signal write_stage_U0_m_axi_gmem_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal write_stage_U0_m_axi_gmem_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal write_stage_U0_m_axi_gmem_ARVALID : STD_LOGIC;
    signal write_stage_U0_m_axi_gmem_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal write_stage_U0_m_axi_gmem_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal write_stage_U0_m_axi_gmem_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal write_stage_U0_m_axi_gmem_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal write_stage_U0_m_axi_gmem_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal write_stage_U0_m_axi_gmem_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal write_stage_U0_m_axi_gmem_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal write_stage_U0_m_axi_gmem_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal write_stage_U0_m_axi_gmem_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal write_stage_U0_m_axi_gmem_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal write_stage_U0_m_axi_gmem_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal write_stage_U0_m_axi_gmem_RREADY : STD_LOGIC;
    signal write_stage_U0_m_axi_gmem_BREADY : STD_LOGIC;
    signal write_stage_U0_out_r_read : STD_LOGIC;
    signal write_stage_U0_stream_out_read : STD_LOGIC;
    signal write_stage_U0_num_pixels_read : STD_LOGIC;
    signal out_r_c_full_n : STD_LOGIC;
    signal out_r_c_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal out_r_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal out_r_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal out_r_c_empty_n : STD_LOGIC;
    signal stream_in_full_n : STD_LOGIC;
    signal stream_in_dout : STD_LOGIC_VECTOR (23 downto 0);
    signal stream_in_num_data_valid : STD_LOGIC_VECTOR (8 downto 0);
    signal stream_in_fifo_cap : STD_LOGIC_VECTOR (8 downto 0);
    signal stream_in_empty_n : STD_LOGIC;
    signal num_pixels_c1_full_n : STD_LOGIC;
    signal num_pixels_c1_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal num_pixels_c1_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal num_pixels_c1_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal num_pixels_c1_empty_n : STD_LOGIC;
    signal stream_out_full_n : STD_LOGIC;
    signal stream_out_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal stream_out_num_data_valid : STD_LOGIC_VECTOR (8 downto 0);
    signal stream_out_fifo_cap : STD_LOGIC_VECTOR (8 downto 0);
    signal stream_out_empty_n : STD_LOGIC;
    signal num_pixels_c_full_n : STD_LOGIC;
    signal num_pixels_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal num_pixels_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal num_pixels_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal num_pixels_c_empty_n : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_entry_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_entry_proc_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_read_stage_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_read_stage_U0_ap_ready : STD_LOGIC;
    signal start_for_write_stage_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_write_stage_U0_full_n : STD_LOGIC;
    signal start_for_write_stage_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_write_stage_U0_empty_n : STD_LOGIC;
    signal start_for_proc_stage_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_proc_stage_U0_full_n : STD_LOGIC;
    signal start_for_proc_stage_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_proc_stage_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component gray_kernel_entry_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        out_r : IN STD_LOGIC_VECTOR (63 downto 0);
        out_r_c_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        out_r_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        out_r_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        out_r_c_full_n : IN STD_LOGIC;
        out_r_c_write : OUT STD_LOGIC );
    end component;


    component gray_kernel_read_stage IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        m_axi_gmem_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_AWREADY : IN STD_LOGIC;
        m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WVALID : OUT STD_LOGIC;
        m_axi_gmem_WREADY : IN STD_LOGIC;
        m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WLAST : OUT STD_LOGIC;
        m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_ARREADY : IN STD_LOGIC;
        m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RVALID : IN STD_LOGIC;
        m_axi_gmem_RREADY : OUT STD_LOGIC;
        m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem_RLAST : IN STD_LOGIC;
        m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
        m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BVALID : IN STD_LOGIC;
        m_axi_gmem_BREADY : OUT STD_LOGIC;
        m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_r : IN STD_LOGIC_VECTOR (63 downto 0);
        stream_in_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        stream_in_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        stream_in_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        stream_in_full_n : IN STD_LOGIC;
        stream_in_write : OUT STD_LOGIC;
        num_pixels : IN STD_LOGIC_VECTOR (31 downto 0);
        num_pixels_c1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        num_pixels_c1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_c1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_c1_full_n : IN STD_LOGIC;
        num_pixels_c1_write : OUT STD_LOGIC );
    end component;


    component gray_kernel_proc_stage IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_in_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        stream_in_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        stream_in_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        stream_in_empty_n : IN STD_LOGIC;
        stream_in_read : OUT STD_LOGIC;
        stream_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        stream_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        stream_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        stream_out_full_n : IN STD_LOGIC;
        stream_out_write : OUT STD_LOGIC;
        num_pixels_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        num_pixels_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_empty_n : IN STD_LOGIC;
        num_pixels_read : OUT STD_LOGIC;
        num_pixels_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        num_pixels_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_c_full_n : IN STD_LOGIC;
        num_pixels_c_write : OUT STD_LOGIC );
    end component;


    component gray_kernel_write_stage IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_AWREADY : IN STD_LOGIC;
        m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WVALID : OUT STD_LOGIC;
        m_axi_gmem_WREADY : IN STD_LOGIC;
        m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WLAST : OUT STD_LOGIC;
        m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_ARREADY : IN STD_LOGIC;
        m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RVALID : IN STD_LOGIC;
        m_axi_gmem_RREADY : OUT STD_LOGIC;
        m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem_RLAST : IN STD_LOGIC;
        m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
        m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BVALID : IN STD_LOGIC;
        m_axi_gmem_BREADY : OUT STD_LOGIC;
        m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        out_r_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        out_r_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        out_r_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        out_r_empty_n : IN STD_LOGIC;
        out_r_read : OUT STD_LOGIC;
        stream_out_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        stream_out_num_data_valid : IN STD_LOGIC_VECTOR (8 downto 0);
        stream_out_fifo_cap : IN STD_LOGIC_VECTOR (8 downto 0);
        stream_out_empty_n : IN STD_LOGIC;
        stream_out_read : OUT STD_LOGIC;
        num_pixels_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        num_pixels_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        num_pixels_empty_n : IN STD_LOGIC;
        num_pixels_read : OUT STD_LOGIC );
    end component;


    component gray_kernel_fifo_w64_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component gray_kernel_fifo_w24_d256_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (23 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (23 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component gray_kernel_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component gray_kernel_fifo_w8_d256_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (8 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component gray_kernel_start_for_write_stage_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component gray_kernel_start_for_proc_stage_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component gray_kernel_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        in_r : OUT STD_LOGIC_VECTOR (63 downto 0);
        out_r : OUT STD_LOGIC_VECTOR (63 downto 0);
        num_pixels : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component gray_kernel_gmem_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (10 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component gray_kernel_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        in_r => in_r,
        out_r => out_r,
        num_pixels => num_pixels,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    gmem_m_axi_U : component gray_kernel_gmem_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 7,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_CACHE_VALUE,
        CH0_USER_RFIFONUM_WIDTH => 11,
        CH0_USER_DW => 8,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16)
    port map (
        AWVALID => m_axi_gmem_AWVALID,
        AWREADY => m_axi_gmem_AWREADY,
        AWADDR => m_axi_gmem_AWADDR,
        AWID => m_axi_gmem_AWID,
        AWLEN => m_axi_gmem_AWLEN,
        AWSIZE => m_axi_gmem_AWSIZE,
        AWBURST => m_axi_gmem_AWBURST,
        AWLOCK => m_axi_gmem_AWLOCK,
        AWCACHE => m_axi_gmem_AWCACHE,
        AWPROT => m_axi_gmem_AWPROT,
        AWQOS => m_axi_gmem_AWQOS,
        AWREGION => m_axi_gmem_AWREGION,
        AWUSER => m_axi_gmem_AWUSER,
        WVALID => m_axi_gmem_WVALID,
        WREADY => m_axi_gmem_WREADY,
        WDATA => m_axi_gmem_WDATA,
        WSTRB => m_axi_gmem_WSTRB,
        WLAST => m_axi_gmem_WLAST,
        WID => m_axi_gmem_WID,
        WUSER => m_axi_gmem_WUSER,
        ARVALID => m_axi_gmem_ARVALID,
        ARREADY => m_axi_gmem_ARREADY,
        ARADDR => m_axi_gmem_ARADDR,
        ARID => m_axi_gmem_ARID,
        ARLEN => m_axi_gmem_ARLEN,
        ARSIZE => m_axi_gmem_ARSIZE,
        ARBURST => m_axi_gmem_ARBURST,
        ARLOCK => m_axi_gmem_ARLOCK,
        ARCACHE => m_axi_gmem_ARCACHE,
        ARPROT => m_axi_gmem_ARPROT,
        ARQOS => m_axi_gmem_ARQOS,
        ARREGION => m_axi_gmem_ARREGION,
        ARUSER => m_axi_gmem_ARUSER,
        RVALID => m_axi_gmem_RVALID,
        RREADY => m_axi_gmem_RREADY,
        RDATA => m_axi_gmem_RDATA,
        RLAST => m_axi_gmem_RLAST,
        RID => m_axi_gmem_RID,
        RUSER => m_axi_gmem_RUSER,
        RRESP => m_axi_gmem_RRESP,
        BVALID => m_axi_gmem_BVALID,
        BREADY => m_axi_gmem_BREADY,
        BRESP => m_axi_gmem_BRESP,
        BID => m_axi_gmem_BID,
        BUSER => m_axi_gmem_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => read_stage_U0_m_axi_gmem_ARVALID,
        I_CH0_ARREADY => gmem_ARREADY,
        I_CH0_ARADDR => read_stage_U0_m_axi_gmem_ARADDR,
        I_CH0_ARLEN => read_stage_U0_m_axi_gmem_ARLEN,
        I_CH0_RVALID => gmem_RVALID,
        I_CH0_RREADY => read_stage_U0_m_axi_gmem_RREADY,
        I_CH0_RDATA => gmem_RDATA,
        I_CH0_RFIFONUM => gmem_RFIFONUM,
        I_CH0_AWVALID => write_stage_U0_m_axi_gmem_AWVALID,
        I_CH0_AWREADY => gmem_AWREADY,
        I_CH0_AWADDR => write_stage_U0_m_axi_gmem_AWADDR,
        I_CH0_AWLEN => write_stage_U0_m_axi_gmem_AWLEN,
        I_CH0_WVALID => write_stage_U0_m_axi_gmem_WVALID,
        I_CH0_WREADY => gmem_WREADY,
        I_CH0_WDATA => write_stage_U0_m_axi_gmem_WDATA,
        I_CH0_WSTRB => write_stage_U0_m_axi_gmem_WSTRB,
        I_CH0_BVALID => gmem_BVALID,
        I_CH0_BREADY => write_stage_U0_m_axi_gmem_BREADY);

    entry_proc_U0 : component gray_kernel_entry_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => entry_proc_U0_ap_start,
        start_full_n => start_for_write_stage_U0_full_n,
        ap_done => entry_proc_U0_ap_done,
        ap_continue => entry_proc_U0_ap_continue,
        ap_idle => entry_proc_U0_ap_idle,
        ap_ready => entry_proc_U0_ap_ready,
        start_out => entry_proc_U0_start_out,
        start_write => entry_proc_U0_start_write,
        out_r => out_r,
        out_r_c_din => entry_proc_U0_out_r_c_din,
        out_r_c_num_data_valid => out_r_c_num_data_valid,
        out_r_c_fifo_cap => out_r_c_fifo_cap,
        out_r_c_full_n => out_r_c_full_n,
        out_r_c_write => entry_proc_U0_out_r_c_write);

    read_stage_U0 : component gray_kernel_read_stage
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => read_stage_U0_ap_start,
        start_full_n => start_for_proc_stage_U0_full_n,
        ap_done => read_stage_U0_ap_done,
        ap_continue => read_stage_U0_ap_continue,
        ap_idle => read_stage_U0_ap_idle,
        ap_ready => read_stage_U0_ap_ready,
        start_out => read_stage_U0_start_out,
        start_write => read_stage_U0_start_write,
        m_axi_gmem_AWVALID => read_stage_U0_m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY => ap_const_logic_0,
        m_axi_gmem_AWADDR => read_stage_U0_m_axi_gmem_AWADDR,
        m_axi_gmem_AWID => read_stage_U0_m_axi_gmem_AWID,
        m_axi_gmem_AWLEN => read_stage_U0_m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE => read_stage_U0_m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST => read_stage_U0_m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK => read_stage_U0_m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE => read_stage_U0_m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT => read_stage_U0_m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS => read_stage_U0_m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION => read_stage_U0_m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER => read_stage_U0_m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID => read_stage_U0_m_axi_gmem_WVALID,
        m_axi_gmem_WREADY => ap_const_logic_0,
        m_axi_gmem_WDATA => read_stage_U0_m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB => read_stage_U0_m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST => read_stage_U0_m_axi_gmem_WLAST,
        m_axi_gmem_WID => read_stage_U0_m_axi_gmem_WID,
        m_axi_gmem_WUSER => read_stage_U0_m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID => read_stage_U0_m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY => gmem_ARREADY,
        m_axi_gmem_ARADDR => read_stage_U0_m_axi_gmem_ARADDR,
        m_axi_gmem_ARID => read_stage_U0_m_axi_gmem_ARID,
        m_axi_gmem_ARLEN => read_stage_U0_m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE => read_stage_U0_m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST => read_stage_U0_m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK => read_stage_U0_m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE => read_stage_U0_m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT => read_stage_U0_m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS => read_stage_U0_m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION => read_stage_U0_m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER => read_stage_U0_m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID => gmem_RVALID,
        m_axi_gmem_RREADY => read_stage_U0_m_axi_gmem_RREADY,
        m_axi_gmem_RDATA => gmem_RDATA,
        m_axi_gmem_RLAST => gmem_RLAST,
        m_axi_gmem_RID => gmem_RID,
        m_axi_gmem_RFIFONUM => gmem_RFIFONUM,
        m_axi_gmem_RUSER => gmem_RUSER,
        m_axi_gmem_RRESP => gmem_RRESP,
        m_axi_gmem_BVALID => ap_const_logic_0,
        m_axi_gmem_BREADY => read_stage_U0_m_axi_gmem_BREADY,
        m_axi_gmem_BRESP => ap_const_lv2_0,
        m_axi_gmem_BID => ap_const_lv1_0,
        m_axi_gmem_BUSER => ap_const_lv1_0,
        in_r => in_r,
        stream_in_din => read_stage_U0_stream_in_din,
        stream_in_num_data_valid => stream_in_num_data_valid,
        stream_in_fifo_cap => stream_in_fifo_cap,
        stream_in_full_n => stream_in_full_n,
        stream_in_write => read_stage_U0_stream_in_write,
        num_pixels => num_pixels,
        num_pixels_c1_din => read_stage_U0_num_pixels_c1_din,
        num_pixels_c1_num_data_valid => num_pixels_c1_num_data_valid,
        num_pixels_c1_fifo_cap => num_pixels_c1_fifo_cap,
        num_pixels_c1_full_n => num_pixels_c1_full_n,
        num_pixels_c1_write => read_stage_U0_num_pixels_c1_write);

    proc_stage_U0 : component gray_kernel_proc_stage
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => proc_stage_U0_ap_start,
        ap_done => proc_stage_U0_ap_done,
        ap_continue => proc_stage_U0_ap_continue,
        ap_idle => proc_stage_U0_ap_idle,
        ap_ready => proc_stage_U0_ap_ready,
        stream_in_dout => stream_in_dout,
        stream_in_num_data_valid => stream_in_num_data_valid,
        stream_in_fifo_cap => stream_in_fifo_cap,
        stream_in_empty_n => stream_in_empty_n,
        stream_in_read => proc_stage_U0_stream_in_read,
        stream_out_din => proc_stage_U0_stream_out_din,
        stream_out_num_data_valid => stream_out_num_data_valid,
        stream_out_fifo_cap => stream_out_fifo_cap,
        stream_out_full_n => stream_out_full_n,
        stream_out_write => proc_stage_U0_stream_out_write,
        num_pixels_dout => num_pixels_c1_dout,
        num_pixels_num_data_valid => num_pixels_c1_num_data_valid,
        num_pixels_fifo_cap => num_pixels_c1_fifo_cap,
        num_pixels_empty_n => num_pixels_c1_empty_n,
        num_pixels_read => proc_stage_U0_num_pixels_read,
        num_pixels_c_din => proc_stage_U0_num_pixels_c_din,
        num_pixels_c_num_data_valid => num_pixels_c_num_data_valid,
        num_pixels_c_fifo_cap => num_pixels_c_fifo_cap,
        num_pixels_c_full_n => num_pixels_c_full_n,
        num_pixels_c_write => proc_stage_U0_num_pixels_c_write);

    write_stage_U0 : component gray_kernel_write_stage
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => write_stage_U0_ap_start,
        ap_done => write_stage_U0_ap_done,
        ap_continue => write_stage_U0_ap_continue,
        ap_idle => write_stage_U0_ap_idle,
        ap_ready => write_stage_U0_ap_ready,
        m_axi_gmem_AWVALID => write_stage_U0_m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY => gmem_AWREADY,
        m_axi_gmem_AWADDR => write_stage_U0_m_axi_gmem_AWADDR,
        m_axi_gmem_AWID => write_stage_U0_m_axi_gmem_AWID,
        m_axi_gmem_AWLEN => write_stage_U0_m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE => write_stage_U0_m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST => write_stage_U0_m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK => write_stage_U0_m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE => write_stage_U0_m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT => write_stage_U0_m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS => write_stage_U0_m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION => write_stage_U0_m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER => write_stage_U0_m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID => write_stage_U0_m_axi_gmem_WVALID,
        m_axi_gmem_WREADY => gmem_WREADY,
        m_axi_gmem_WDATA => write_stage_U0_m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB => write_stage_U0_m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST => write_stage_U0_m_axi_gmem_WLAST,
        m_axi_gmem_WID => write_stage_U0_m_axi_gmem_WID,
        m_axi_gmem_WUSER => write_stage_U0_m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID => write_stage_U0_m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY => ap_const_logic_0,
        m_axi_gmem_ARADDR => write_stage_U0_m_axi_gmem_ARADDR,
        m_axi_gmem_ARID => write_stage_U0_m_axi_gmem_ARID,
        m_axi_gmem_ARLEN => write_stage_U0_m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE => write_stage_U0_m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST => write_stage_U0_m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK => write_stage_U0_m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE => write_stage_U0_m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT => write_stage_U0_m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS => write_stage_U0_m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION => write_stage_U0_m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER => write_stage_U0_m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID => ap_const_logic_0,
        m_axi_gmem_RREADY => write_stage_U0_m_axi_gmem_RREADY,
        m_axi_gmem_RDATA => ap_const_lv8_0,
        m_axi_gmem_RLAST => ap_const_logic_0,
        m_axi_gmem_RID => ap_const_lv1_0,
        m_axi_gmem_RFIFONUM => ap_const_lv11_0,
        m_axi_gmem_RUSER => ap_const_lv1_0,
        m_axi_gmem_RRESP => ap_const_lv2_0,
        m_axi_gmem_BVALID => gmem_BVALID,
        m_axi_gmem_BREADY => write_stage_U0_m_axi_gmem_BREADY,
        m_axi_gmem_BRESP => gmem_BRESP,
        m_axi_gmem_BID => gmem_BID,
        m_axi_gmem_BUSER => gmem_BUSER,
        out_r_dout => out_r_c_dout,
        out_r_num_data_valid => out_r_c_num_data_valid,
        out_r_fifo_cap => out_r_c_fifo_cap,
        out_r_empty_n => out_r_c_empty_n,
        out_r_read => write_stage_U0_out_r_read,
        stream_out_dout => stream_out_dout,
        stream_out_num_data_valid => stream_out_num_data_valid,
        stream_out_fifo_cap => stream_out_fifo_cap,
        stream_out_empty_n => stream_out_empty_n,
        stream_out_read => write_stage_U0_stream_out_read,
        num_pixels_dout => num_pixels_c_dout,
        num_pixels_num_data_valid => num_pixels_c_num_data_valid,
        num_pixels_fifo_cap => num_pixels_c_fifo_cap,
        num_pixels_empty_n => num_pixels_c_empty_n,
        num_pixels_read => write_stage_U0_num_pixels_read);

    out_r_c_U : component gray_kernel_fifo_w64_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_out_r_c_din,
        if_full_n => out_r_c_full_n,
        if_write => entry_proc_U0_out_r_c_write,
        if_dout => out_r_c_dout,
        if_num_data_valid => out_r_c_num_data_valid,
        if_fifo_cap => out_r_c_fifo_cap,
        if_empty_n => out_r_c_empty_n,
        if_read => write_stage_U0_out_r_read);

    stream_in_U : component gray_kernel_fifo_w24_d256_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_stage_U0_stream_in_din,
        if_full_n => stream_in_full_n,
        if_write => read_stage_U0_stream_in_write,
        if_dout => stream_in_dout,
        if_num_data_valid => stream_in_num_data_valid,
        if_fifo_cap => stream_in_fifo_cap,
        if_empty_n => stream_in_empty_n,
        if_read => proc_stage_U0_stream_in_read);

    num_pixels_c1_U : component gray_kernel_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_stage_U0_num_pixels_c1_din,
        if_full_n => num_pixels_c1_full_n,
        if_write => read_stage_U0_num_pixels_c1_write,
        if_dout => num_pixels_c1_dout,
        if_num_data_valid => num_pixels_c1_num_data_valid,
        if_fifo_cap => num_pixels_c1_fifo_cap,
        if_empty_n => num_pixels_c1_empty_n,
        if_read => proc_stage_U0_num_pixels_read);

    stream_out_U : component gray_kernel_fifo_w8_d256_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => proc_stage_U0_stream_out_din,
        if_full_n => stream_out_full_n,
        if_write => proc_stage_U0_stream_out_write,
        if_dout => stream_out_dout,
        if_num_data_valid => stream_out_num_data_valid,
        if_fifo_cap => stream_out_fifo_cap,
        if_empty_n => stream_out_empty_n,
        if_read => write_stage_U0_stream_out_read);

    num_pixels_c_U : component gray_kernel_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => proc_stage_U0_num_pixels_c_din,
        if_full_n => num_pixels_c_full_n,
        if_write => proc_stage_U0_num_pixels_c_write,
        if_dout => num_pixels_c_dout,
        if_num_data_valid => num_pixels_c_num_data_valid,
        if_fifo_cap => num_pixels_c_fifo_cap,
        if_empty_n => num_pixels_c_empty_n,
        if_read => write_stage_U0_num_pixels_read);

    start_for_write_stage_U0_U : component gray_kernel_start_for_write_stage_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_write_stage_U0_din,
        if_full_n => start_for_write_stage_U0_full_n,
        if_write => entry_proc_U0_start_write,
        if_dout => start_for_write_stage_U0_dout,
        if_empty_n => start_for_write_stage_U0_empty_n,
        if_read => write_stage_U0_ap_ready);

    start_for_proc_stage_U0_U : component gray_kernel_start_for_proc_stage_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_proc_stage_U0_din,
        if_full_n => start_for_proc_stage_U0_full_n,
        if_write => read_stage_U0_start_write,
        if_dout => start_for_proc_stage_U0_dout,
        if_empty_n => start_for_proc_stage_U0_empty_n,
        if_read => proc_stage_U0_ap_ready);





    ap_sync_reg_entry_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_read_stage_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_read_stage_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_read_stage_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_read_stage_U0_ap_ready <= ap_sync_read_stage_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    ap_done <= write_stage_U0_ap_done;
    ap_idle <= (write_stage_U0_ap_idle and read_stage_U0_ap_idle and proc_stage_U0_ap_idle and entry_proc_U0_ap_idle);
    ap_ready <= ap_sync_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_entry_proc_U0_ap_ready <= (entry_proc_U0_ap_ready or ap_sync_reg_entry_proc_U0_ap_ready);
    ap_sync_read_stage_U0_ap_ready <= (read_stage_U0_ap_ready or ap_sync_reg_read_stage_U0_ap_ready);
    ap_sync_ready <= (ap_sync_read_stage_U0_ap_ready and ap_sync_entry_proc_U0_ap_ready);
    entry_proc_U0_ap_continue <= ap_const_logic_1;
    entry_proc_U0_ap_start <= ((ap_sync_reg_entry_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    gmem_BID <= ap_const_lv1_0;
    gmem_BRESP <= ap_const_lv2_0;
    gmem_BUSER <= ap_const_lv1_0;
    gmem_RID <= ap_const_lv1_0;
    gmem_RLAST <= ap_const_logic_0;
    gmem_RRESP <= ap_const_lv2_0;
    gmem_RUSER <= ap_const_lv1_0;
    proc_stage_U0_ap_continue <= ap_const_logic_1;
    proc_stage_U0_ap_start <= start_for_proc_stage_U0_empty_n;
    read_stage_U0_ap_continue <= ap_const_logic_1;
    read_stage_U0_ap_start <= ((ap_sync_reg_read_stage_U0_ap_ready xor ap_const_logic_1) and ap_start);
    start_for_proc_stage_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_write_stage_U0_din <= (0=>ap_const_logic_1, others=>'-');
    write_stage_U0_ap_continue <= ap_const_logic_1;
    write_stage_U0_ap_start <= start_for_write_stage_U0_empty_n;
end behav;
